# Generated by Django 5.1 on 2024-08-27 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o seu nome', max_length=50)),
                ('sobrenome', models.CharField(help_text='Digite o seu nome', max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField(default=None, null=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('telefone', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da despesa', max_length=25, unique=True)),
                ('descricao', models.TextField(help_text='Digite a descrição da despesa')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('ano', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do setor', max_length=20, unique=True)),
                ('telefone', models.CharField(default=None, help_text='Digite o contato do setor', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EaseFinance.funcionario')),
                ('data_promocao', models.DateField()),
                ('descricao_atividades', models.CharField(max_length=300)),
            ],
            bases=('EaseFinance.funcionario',),
        ),
        migrations.CreateModel(
            name='OrcamentoSetorAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='valor')),
                ('orcamento_ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EaseFinance.orcamentoanual')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EaseFinance.setor')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoDespesaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesa', to='EaseFinance.despesa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor', to='EaseFinance.setor')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EaseFinance.setor'),
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Realocao do Orcamento Interno das Despesas no Setor'), (2, 'Compras de Produtos ou equipamentos'), (3, 'Despesas em Geral'), (4, 'Transferencia de Valores de  Orcamento entre Setores')], default=1)),
                ('motivo', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('prazo', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('observacao', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('despesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EaseFinance.despesa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('funcionario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EaseFinance.funcionario')),
                ('descricao_atividades', models.CharField(max_length=300)),
                ('equipe', models.ManyToManyField(related_name='equipe', to='EaseFinance.funcionario')),
            ],
            bases=('EaseFinance.funcionario',),
        ),
    ]
