# Generated by Django 5.1 on 2024-08-27 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EaseFinance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Compras de Produtos ou equipamentos'), (2, 'Despesas em Geral'), (3, 'Realocao do Orcamento Interno das Despesas no Setor'), (4, 'Transferencia de Valores de  Orcamento entre Setores')], default=1),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
