# Generated by Django 5.1 on 2024-08-28 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EaseFinance', '0002_alter_solicitacao_tipo_alter_solicitacao_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EaseFinance.despesa'),
        ),
    ]
